<?php

declare(strict_types=1);

namespace Nandan108\Attrecord;

use Nandan108\Attrecord\Schema\ColumnDefinition;
use Nandan108\Attrecord\Schema\TableSchema;

/**
 * Strategy for dialect-specific SQL generation.
 *
 * Used only in RecordSet::upsertAll() where values are embedded directly in the SQL string.
 * Single-record save() uses parameterised queries through DbSession instead.
 *
 * @api
 */
interface SqlDialect
{
    /**
     * Whether binary parameter values must be bound as a typed LOB rather than a plain string.
     *
     * Return false for MySQL/MariaDB, where raw bytes bind through an ordinary string
     * parameter. Return true for PostgreSQL, where PDO_pgsql treats a positional parameter as
     * UTF-8 text and rejects non-UTF-8 bytes — so binary values must be wrapped in a
     * {@see BinaryParam} (bound as PDO::PARAM_LOB).
     *
     * When false, {@see ColumnSerializer::toParam()} leaves binary values as raw byte strings,
     * so a consumer's custom DbSession that only handles scalars keeps working unchanged.
     */
    public function bindsBinaryAsLob(): bool;

    /**
     * Convert a PHP value to a SQL literal for embedding in a bulk statement.
     * Must return a properly quoted/escaped string that is safe to embed verbatim.
     */
    public function toLiteral(mixed $value, ColumnDefinition $col): string;

    /** Quote a table or column identifier (e.g. backticks for MySQL, double quotes for Postgres). */
    public function quoteIdentifier(string $name): string;

    /**
     * Escape LIKE wildcards (%, _) and the backslash escape character in a user-supplied
     * literal so it matches verbatim inside a LIKE / NOT LIKE pattern.
     *
     * Use this when building a pattern from user input:
     *
     *   $safe = $dialect->escapeLikeWildcards($userInput);
     *   WhereClause::whereLike('name', '%'.$safe.'%');
     *   // SQL: (name LIKE ?)  or  (name LIKE ? ESCAPE '\')  depending on dialect
     *
     * Both MySQL and PostgreSQL use backslash as the escape character here.
     * The required ESCAPE clause difference is handled transparently in the SQL
     * generated by WhereClause — you only need to escape the value itself.
     */
    public function escapeLikeWildcards(string $literal): string;

    /**
     * SQL suffix appended after the ? placeholder in a LIKE / NOT LIKE predicate.
     *
     * MySQL treats backslash as the LIKE escape character by default — no suffix needed.
     * PostgreSQL (standard_conforming_strings=on, default since 9.1) does not — the
     * escape character must be declared explicitly with ESCAPE '\'.
     *
     * Returns '' for MySQL/MariaDB, " ESCAPE '\\'" for PostgreSQL.
     */
    public function likeEscapeSuffix(): string;

    /**
     * SQL suffix appended to a single-record INSERT to retrieve the generated PK.
     *
     * Return an empty string for MySQL/MariaDB where lastInsertId() is reliable.
     * Return "RETURNING {quotedPk}" for PostgreSQL (PDO's lastInsertId() requires an
     * explicit sequence name in PG and is therefore unreliable without it).
     *
     * @param string $quotedPkColumn Already-quoted PK column name (via quoteIdentifier())
     */
    public function insertReturningSuffix(string $quotedPkColumn): string;

    /**
     * Whether this engine supports a `RETURNING` clause on INSERT **and** UPDATE, letting a write
     * fold its read-back (fired defaults, generated columns) into the write statement instead of a
     * separate SELECT. True for PostgreSQL and SQLite (3.35+); false for MySQL/MariaDB, which have no
     * `RETURNING` (MariaDB has it for INSERT/DELETE only, not UPDATE — so it stays on the SELECT path).
     */
    public function supportsReturning(): bool;

    /**
     * The row-locking clause for a `SELECT … FOR UPDATE` read.
     *
     * Return `'FOR UPDATE'` for engines with row-level pessimistic locking (MySQL/MariaDB,
     * PostgreSQL). Return `''` for engines that have no such clause (SQLite serializes writers
     * at the database level, so there is nothing to acquire per-row) — callers append this to
     * the ORDER BY, so an empty string simply yields a plain ordered SELECT.
     */
    public function forUpdateClause(): string;

    /**
     * Statements to run once when a connection is opened, to bring it to a sane baseline for
     * this engine (e.g. SQLite `PRAGMA journal_mode=WAL`, `PRAGMA busy_timeout=…`,
     * `PRAGMA foreign_keys=ON`). {@see Connection} executes these on construction.
     *
     * This is *declared* here (as data) rather than executed by the dialect, so the dialect
     * stays a pure SQL-string strategy with no connection/I-O of its own. Return an empty list
     * when the engine needs no such setup (MySQL/MariaDB and PostgreSQL, by default).
     *
     * @return list<string>
     */
    public function connectionInitStatements(): array;

    /**
     * Build a plain bulk INSERT for new records (no known PK).
     *
     * @param string             $tableName   Unquoted table name
     * @param list<string>       $columnNames Column names to insert (unquoted; PK excluded)
     * @param list<list<string>> $rows        Each inner list is ordered SQL literals per column
     */
    public function buildBulkInsert(
        string $tableName,
        array $columnNames,
        array $rows,
    ): string;

    /**
     * A reference to the *incoming* (would-be-inserted) row's value for a column, usable inside an
     * upsert's conflict-UPDATE SET clause: `VALUES(col)` on MySQL/MariaDB, `EXCLUDED.col` on
     * PostgreSQL/SQLite. Renders an **identifier reference**, not a bound value.
     *
     * @param string $column Unquoted column name
     */
    public function incomingRef(string $column): string;

    /**
     * Build a parameterized INSERT … ON CONFLICT UPDATE for a single record.
     *
     * MySQL emits `ON DUPLICATE KEY UPDATE`; PostgreSQL/SQLite `ON CONFLICT (cols) DO UPDATE SET`
     * (and `DO NOTHING` when `$updateCols` is empty). Each SET entry is keyed by column name and
     * carries either `null` — meaning the default "copy the incoming value" ({@see incomingRef()}) —
     * or a **raw SQL expression string** (already dialect-portable; its bound values are supplied by
     * the caller, spliced after the INSERT `VALUES` params in this map's iteration order).
     *
     * @param string                 $tableName    Unquoted table name
     * @param list<string>           $columnNames  Columns to insert (unquoted; autoIncrement PK excluded)
     * @param list<string>           $conflictCols Unique key columns for conflict detection
     * @param array<string, ?string> $updateCols   Column → SET expression (null = copy the incoming value)
     */
    public function buildSingleUpsertSql(
        string $tableName,
        array $columnNames,
        array $conflictCols,
        array $updateCols,
    ): string;

    /**
     * Build the three SQL statements for a deadlock-safe bulk upsert.
     *
     * Step 1 (create): INSERT IGNORE — inserts genuinely new rows; silently skips existing ones.
     * Step 2 (lock):   SELECT pk … ORDER BY pk ASC FOR UPDATE — acquires row locks in a
     *                  deterministic order, eliminating deadlocks from lock-order inversion.
     * Step 3 (update): CASE-based UPDATE — applies column values in a single statement.
     *                  null when $updateColumns is empty (insert-only scenario).
     *
     * **Per-row dirty scoping.** Each update column emits a `WHEN pk THEN value` only for the rows
     * that actually changed it (per $rowDirtyColumns); rows that did not fall through `ELSE <col>`,
     * preserving the column's live value. A column changed by *every* row needs no `ELSE` and
     * collapses to the plain all-rows form. This lets a heterogeneous batch — records each carrying
     * a different subset of fields — update each row's own fields without clobbering columns it
     * never supplied. When $rowDirtyColumns is empty (no dirty info), every row participates in
     * every column (the original behaviour).
     *
     * All three statements must run inside the same transaction.
     *
     * @param string                    $tableName       Unquoted table name
     * @param string                    $pkColumn        PK column name (unquoted)
     * @param list<string>              $columnNames     All columns to write, including PK (unquoted)
     * @param list<list<string>>        $rows            SQL literals per row, in $columnNames order
     * @param list<string>              $updateColumns   Non-PK columns to overwrite on conflict
     * @param list<array<string, bool>> $rowDirtyColumns Per row (aligned to $rows): the set of column
     *                                                   names that row changed. Empty ⇒ treat every
     *                                                   row as having changed every column.
     */
    public function buildUpsertSql(
        string $tableName,
        string $pkColumn,
        array $columnNames,
        array $rows,
        array $updateColumns,
        array $rowDirtyColumns = [],
    ): UpsertSql;

    /**
     * Emit a `CREATE TABLE` statement for a compiled {@see TableSchema}.
     *
     * Includes primary key, unique keys, secondary indexes, and FOREIGN KEY
     * constraints derived from owning-side relations. Table options (engine,
     * charset, collation, comment) are dialect-dependent and may be ignored
     * by non-MySQL dialects.
     *
     * @param bool $ifNotExists When true, emits `CREATE TABLE IF NOT EXISTS`. Use for idempotent install paths; do not use in migration emission where the table is expected to be absent.
     *
     * @throws Exception\SchemaException for invalid metadata that the schema builder did not already catch
     */
    public function buildCreateTable(TableSchema $schema, bool $ifNotExists = false): string;
}
