<?php

declare(strict_types=1);

namespace Nandan108\Attrecord;

use Nandan108\Attrecord\Schema\ColumnDefinition;

/**
 * Strategy for dialect-specific SQL generation.
 *
 * Used only in RecordSet::saveAll() where values are embedded directly in the SQL string.
 * Single-record save() uses parameterised queries through DbSession instead.
 *
 * @api
 */
interface SqlDialect
{
    /**
     * Convert a PHP value to a SQL literal for embedding in a bulk statement.
     * Must return a properly quoted/escaped string that is safe to embed verbatim.
     */
    public function toLiteral(mixed $value, ColumnDefinition $col): string;

    /** Quote a table or column identifier (e.g. backticks for MySQL, double quotes for Postgres). */
    public function quoteIdentifier(string $name): string;

    /**
     * Escape LIKE wildcards (%, _) and the backslash escape character in a user-supplied
     * literal so it matches verbatim inside a LIKE / NOT LIKE pattern.
     *
     * Use this when building a pattern from user input:
     *
     *   $safe = $dialect->escapeLikeWildcards($userInput);
     *   WhereClause::whereLike('name', '%'.$safe.'%');
     *   // SQL: (name LIKE ?)  or  (name LIKE ? ESCAPE '\')  depending on dialect
     *
     * Both MySQL and PostgreSQL use backslash as the escape character here.
     * The required ESCAPE clause difference is handled transparently in the SQL
     * generated by WhereClause — you only need to escape the value itself.
     */
    public function escapeLikeWildcards(string $literal): string;

    /**
     * SQL suffix appended after the ? placeholder in a LIKE / NOT LIKE predicate.
     *
     * MySQL treats backslash as the LIKE escape character by default — no suffix needed.
     * PostgreSQL (standard_conforming_strings=on, default since 9.1) does not — the
     * escape character must be declared explicitly with ESCAPE '\'.
     *
     * Returns '' for MySQL/MariaDB, " ESCAPE '\\'" for PostgreSQL.
     */
    public function likeEscapeSuffix(): string;

    /**
     * SQL suffix appended to a single-record INSERT to retrieve the generated PK.
     *
     * Return an empty string for MySQL/MariaDB where lastInsertId() is reliable.
     * Return "RETURNING {quotedPk}" for PostgreSQL (PDO's lastInsertId() requires an
     * explicit sequence name in PG and is therefore unreliable without it).
     *
     * @param string $quotedPkColumn Already-quoted PK column name (via quoteIdentifier())
     */
    public function insertReturningSuffix(string $quotedPkColumn): string;

    /**
     * Build a plain bulk INSERT for new records (no known PK).
     *
     * @param string             $tableName   Unquoted table name
     * @param list<string>       $columnNames Column names to insert (unquoted; PK excluded)
     * @param list<list<string>> $rows        Each inner list is ordered SQL literals per column
     */
    public function buildBulkInsert(
        string $tableName,
        array $columnNames,
        array $rows,
    ): string;

    /**
     * Build a parameterized INSERT … ON CONFLICT UPDATE for a single record.
     *
     * MySQL uses ON DUPLICATE KEY UPDATE col = VALUES(col); conflictCols are accepted
     * but not required in the SQL (MySQL resolves the conflict implicitly).
     * PostgreSQL uses ON CONFLICT (cols) DO UPDATE SET col = EXCLUDED.col.
     *
     * @param string       $tableName    Unquoted table name
     * @param list<string> $columnNames  Columns to insert (unquoted; autoIncrement PK excluded)
     * @param list<string> $conflictCols Unique key columns for conflict detection
     * @param list<string> $updateCols   Columns to overwrite on conflict
     */
    public function buildSingleUpsertSql(
        string $tableName,
        array $columnNames,
        array $conflictCols,
        array $updateCols,
    ): string;

    /**
     * Build the three SQL statements for a deadlock-safe bulk upsert.
     *
     * Step 1 (create): INSERT IGNORE — inserts genuinely new rows; silently skips existing ones.
     * Step 2 (lock):   SELECT pk … ORDER BY pk ASC FOR UPDATE — acquires row locks in a
     *                  deterministic order, eliminating deadlocks from lock-order inversion.
     * Step 3 (update): CASE-based UPDATE — applies column values in a single statement.
     *                  null when $updateColumns is empty (insert-only scenario).
     *
     * All three statements must run inside the same transaction.
     *
     * @param string             $tableName     Unquoted table name
     * @param string             $pkColumn      PK column name (unquoted)
     * @param list<string>       $columnNames   All columns to write, including PK (unquoted)
     * @param list<list<string>> $rows          SQL literals per row, in $columnNames order
     * @param list<string>       $updateColumns Non-PK columns to overwrite on conflict
     */
    public function buildUpsertSql(
        string $tableName,
        string $pkColumn,
        array $columnNames,
        array $rows,
        array $updateColumns,
    ): UpsertSql;
}
